### ISSUE TITLE
Research and Plan out what data you want to collect

### ISSUE THREAD

**Issue by bellh14** [bellh14/AIMProjectF2023#1]
# Deliverable

## Objectives

1. What data do you want to collect?
2. Why do you want that data?
3. How do you intend to obtain that data?
4. Pick a dataset issue you would be interested or more than one
5. You will work together on at least one of them

### Submission

- First refer to the wiki section on branch naming conventions for how this repo will be structured.
- I have already created a branch for this issue, so you just have to switch to that  branch and then add your answers to these questions.
- If you are working together with someone for this, you do not both have to submit, but add both of your names.
- Once you have added your submission to the branch, create a pull request from the website.  

## Reference

The goal is to give recommendations to the user to help them improve their financial standing and achieve their goals. This is a very broad scope for data collection so this is why we need a plan for what we need and what to skip.

Here are some examples that will be needed:
- User Income
- User Expenses
- Investment / Savings account goals
- User Specific Goals: Home / Car / Wedding
- General Goals: Vacations / Hobbies, etc...
- Budgets: basically combine income expenses with extra details
- Stock Market

### Methods

Since this is so broad, it is fairly tricky to collect all of it with one method.
I have already looked into this a little, but you should do your own research and discuss amongst each other what you think.

Example methods:
- Find an already made data set
- Find an api to call to collect information
- Scrape the data off the web manually yourself
- Synthetic data generation

I expect this project will take most if not all of these, but it is up to you to figure out which ones you want to use.

## As always let me know if you have questions

**Comment by swayam528** [comment]
What data would you like to collect? Financial statements. Although there's a fairly vast list, I want to focus on collecting data on 3 specific ones: balance sheets, income statements, and cash flow statements. To analyze the company's health, we want to collect these 3 financial statements for at least the last five years to understand the company's financials better and fully and tailor recommendations for them. 
Why do you want that data? These three financial statements specifically help provide for a corporation's overall financial health. Specifically, through balance sheets over the last five years, we can understand important information such as the company's liquidity through the current ratio, and if less than one can recommend the company to focus more on its finances so that it can have fewer liabilities than assets. Income statements can help us understand the measures of net income over the last 5 financial periods and if we see a declining net income we can suggest ways for a company to reduce expenses and maximize revenues. Lastly, a statement of cash flows can help us find out where all the cash is being redirected and help us understand the root cause for the lack of liquidity for a company.
How do you intend to obtain that data? This data can be accumulated through previously audited financial statements for a certain company that we analyze, and we can use the yahoo finance API to do so.
Pick a dataset issue you would be interested in or more than one. (There are a few issues already created that I expect we need, but if you come up with more, they will be added) Finding a data set of financial statements and scraping data manually from https://www.kaggle.com/datasets/securities-exchange-commission/financial-statement-extracts
